services:
  - type: web
    name: hotelsewa-api
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: mysql://root@209.50.241.46:3306/hotelsewa
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 4000
